# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed43cc28c032b88fb7be18e89bff46cc10134c8058a16deb489382c7067774bc7570a43b06fbe9ae0a886da1b3e6e1b49244d2ff32424419cfc64f9433afb25a

test:
  secret_key_base: 5312927e427ab56c7f7a9082aa2463b48b12446c2e8cfaea6a2ffd92ffc1ca71cd92ec109e87537cda2393ad16c49f3ab3d85f6c28d67bf409732475445914cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
